name: ecommerce
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  cached_network_image: 3.3.1
  gap: 3.0.1
  dio:
  built_value:
  built_collection:
  flutter_bloc:
  logger: 2.5.0
  get_it:
  rxdart: 0.28.0
  flutter_styled_toast: 2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  build_runner:
  built_value_generator:

flutter:
  uses-material-design: true
